#!/bin/sh

### BEGIN INIT INFO
# Provides:          aspectow
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop Aspectran daemons
# Description:       Start/stop Aspectran daemons
### END INIT INFO

. /home/aspectran/aspectow/app.conf

DAEMON_OUT="$DEPLOY_DIR/logs/daemon.out"
DAEMON_ERR="$DEPLOY_DIR/logs/daemon.err"

"$DEPLOY_DIR/bin/jsvc-daemon.sh" \
  --proc-name "$PROC_NAME" \
  --pid-file "$PID_FILE" \
  --user "$DAEMON_USER" \
  $1

[ -f "$PID_FILE" ] && chown "$DAEMON_USER" "$PID_FILE"
[ -f "$DAEMON_OUT" ] && chown "$DAEMON_USER" "$DAEMON_OUT"
[ -f "$DAEMON_ERR" ] && chown "$DAEMON_USER" "$DAEMON_ERR"